  
org: innovationit
app: rc-encourage-api
service: rc-encourage-api
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 15
  region: us-east-1
  environment:
    MEDIA_TABLE_NAME: ${env:MEDIA_TABLE_NAME}
    MEDIA_TABLE_ARN: ${env:MEDIA_TABLE_ARN}
    GET_ENCOURAGE_ROUTE_NAME: rc-encourage-api-${opt:stage, self:provider.stage}-getEncouragement
    POST_ENCOURAGE_ROUTE_NAME: rc-encourage-api-${opt:stage, self:provider.stage}-createEncouragement
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:ListStreams
      Resource:
        - ${self:provider.environment.MEDIA_TABLE_NAME}/stream/*
        - ${self:provider.environment.MEDIA_TABLE_ARN}/index/*

functions:
  #createEncouragement:
   # handler: api/createEncouragement/index.handler
  getEncouragement:
    handler: api/getEncouragement/index.handler
## resources:
  ## Resources:
    ## KongRouteResource:
      ## Type: "Custom::KongRoute"
      ## Properties:
        ## ServiceToken: ${env:KONG_ROUTE_ARN}
        ## name: ${self:provider.environment.POST_ENCOURAGE_ROUTE_NAME}
        ## methods: ["POST","OPTIONS"]
        ## paths: ["/${opt:stage, self:provider.stage}/encourages"]
        ## aws_region: "us-east-1"
    ## KongRouteGetResource:
      ## Type: "Custom::KongRoute"
      ## Properties:
        ## ServiceToken: ${env:KONG_ROUTE_ARN}
        ## name:  ${self:provider.environment.GET_ENCOURAGE_ROUTE_NAME}
        ## methods: ["GET", "OPTIONS"]
        ## paths: ["/${opt:stage, self:provider.stage}/encourages/(?<beneficiaryId>[^/]+)"]
        ## aws_region: "us-east-1"
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore